version: '3.3'
services:
  rocky:
    restart: unless-stopped
    ports:
      - '5901:5901'
      - '6901:6901'
    image: consol/rocky-xfce-vnc
    command: firefox --new-window https://orteil.dashnet.org/cookieclicker/
    volumes:
      - ./Downloads:/headless/Downloads/
      - ./.mozilla:/headless/.mozilla/
    environment:
      - VNC_PW=cookie
      - VNC_RESOLUTION=1280x1024

